### PR TITLE
Update LocallyStoredImage.php to remove temporary files when not needed anymore

### PR DESCRIPTION
**Pull request by r-da**
Added the destructor to remove the tmp file storing the image.
Without this patch the tmp folder will be filled up with a lot of image files.

### CODE REVIEW

**Comment by scotteh** [comment]
Nice pickup. Might be worth extending this to handle clean-up after fatal errors (deconstructors aren't called in this case), what are your thoughts?

**Comment by r-da** [comment]
After my change (and proposed pull) and a few days of testing, I have some
residual tmp files (all derived from errors in image recovery).
I have changed ImageUtils->storeImagesToLocalFile to handle this issue,
I'll let you know if it solve the problem after a few days of testing.

What do you think?

2017-03-11 1:46 GMT+01:00 Andrew Scott <notifications@github.com>:

**Comment by scotteh** [comment]
Great - Let me know how it goes :)

**Comment by koxon** [comment]
Hi all,
Any updates on this?

**Comment by r-da** [comment]
Hi all,
no more growing tmp files, the change worked.

2017-08-01 15:37 GMT+02:00 Nicolas Menciere <notifications@github.com>:

**Pull request merged**
